{% set name = "minikanren" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/minikanren-{{ version }}.tar.gz
  sha256: c030e3e9a3fa5f372f84b66966776a8dc63b16b98768b78be0401982b892e00d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - cons >=0.4.0
    - etuples >=0.3.1
    - logical-unification >=0.4.1
    - multipledispatch
    - toolz
    - typing_extensions

test:
  imports:
    - minikanren
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pythological/kanren
  dev_url: https://github.com/pythological/kanren
  summary: Relational programming in Python
  description: An extensible, lightweight relational/logic programming DSL written in pure Python
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
