{% set version = "1.0.4" %}

package:
  name: minikanren
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/miniKanren/minikanren-{{ version }}.tar.gz
  sha256: 5743c5020dcb7cb376c25155506d63072144a2b93f04892855777a8136eacc59
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - toolz
    - cons >=0.4.0
    - multipledispatch
    - etuples >=0.3.1
    - logical-unification >=0.4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - kanren

about:
  home: https://github.com/pythological/kanren
  license: BSD-3-Clause
  summary: An extensible, lightweight relational/logic programming DSL written in pure Python
  license_file: LICENSE.txt
  dev_url: https://github.com/pythological/kanren

extra:
  recipe-maintainers:
    - brandonwillard
